config/routes.rb
Rails.application.routes.draw do
  get "/dashboard" => 'dashboard#index', as: :dashboard
  get 'dashboard/properties'
  get 'dashboard/reports'
  devise_for :accounts
  resources :properties
  resources :posts
  root to: 'public#main'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/layouts/nav/_dashboard.html.erb
<nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
  <a class="navbar-brand col-md-3 col-lg-2 mr-0 px-3" href="#">Property Finder</a>
  <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-toggle="collapse" data-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <input class="form-control form-control-dark w-100" type="text" placeholder="Search" aria-label="Search">
  <ul class="navbar-nav px-3">
    <li class="nav-item text-nowrap">
      <%= link_to "Log out" , destroy_account_session_path, method: :delete ,class: "nav-link"  %>
    </li>
  </ul>
</nav>

app/views/layouts/nav/_footer.html.erb
<footer class="container">
  <p>&copy; Property Finder 2023</p>
</footer>

app/views/layouts/nav/_public.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <a class="navbar-brand" href="#">Property Finder</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
       <li class="nav-item">
          <% if account_signed_in? %>
          <%= link_to "Dashboard", dashboard_path, class: "nav-link" %>
          <% else %>
          <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
          <% end %>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="#">Latest</a>
      </li>

      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
        <div class="dropdown-menu" aria-labelledby="dropdown01">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="#">News</a>
      </li>
      </li>
        <li class="nav-item">
        <a class="nav-link" href="#">Advertising</a>
      </li>
       <% if account_signed_in? %>
      <%= link_to "Log Out", destroy_account_session_path, method: :delete, class: 'nav-link' %>
      <% else %>
      </li>
        <li class="nav-item">
        <%= link_to 'Log In', new_account_session_path, class: 'nav-link'%>
      </li>
      <li class="nav-item">
        <%= link_to 'Sign Up', new_account_registration_path, class: 'nav-link'%>
      </li>
      <% end %>
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

app/views/layouts/nav/_sidebar.html.erb
<nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
      <div class="sidebar-sticky pt-3" bis_skin_checked="1">
        <%# <ul class="nav flex-column">
          <%= render "layouts/nav/#{ current_account.admin? ? 'admin' : 'user' }"%>
        </ul> %>

        <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
          <span>Settings</span>
        </h6>
        <ul class="nav flex-column mb-2">
          <%# <li class="nav-item">
            <%= link_to profile_path(current_account), class: "nav-link" do %>
            <%# <i data-feather="file-text"></i> %>
            <%# My Profile %>
            <%# <% end %> %>
          <%# </li> %> %>
          <li class="nav-item">
            <%= link_to edit_account_registration_path ,class: "nav-link" do %>
            <i data-feather="settings"></i>
            Account Settings
            <% end %>
          </li>
        </ul>
      </div>
    </nav>