config/routes.rb
Rails.application.routes.draw do
  get "/dashboard" => 'dashboard#index', as: :dashboard
  get 'dashboard/properties'
  get 'dashboard/reports'
  devise_for :accounts
  resources :properties
  resources :posts
  root to: 'public#main'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/property.rb
# frozen_string_literal: true

class Property < ApplicationRecord
    mount_uploader :photo, PhotoUploader
    belongs_to :account
  
    scope :latest, -> { order created_at: :desc }
  
    scope :sold, -> { where(for_sale: true, status: 'sold') }
    scope :for_sale, -> { where(for_sale: true, status: 'available') }
    scope :leased, -> { where(for_sale: false, status: 'leased') }
    scope :for_rent, -> { where(for_sale: false, status: 'available') }
  end

app/controllers/properties_controller.rb
# frozen_string_literal: true

class PropertiesController < ApplicationController
  before_action :set_property, only: %i[show edit update destroy]
  before_action :authenticate_account!, only: %i[new create destroy]
  before_action :set_sidebar, except: %i[show]

  # GET /properties
  # GET /properties.json
  def index
    @properties = Property.all
  end

  # GET /properties/1
  # GET /properties/1.json
  def show
    @agent = @property.account
    @agent_properties = Property.where(account_id: @agent.id).where.not(id: @property.id)
  end

  # GET /properties/new
  def new
    @property = Property.new
  end

  # GET /properties/1/edit
  def edit; end

  # POST /properties
  # POST /properties.json
  def create
    @property = Property.new(property_params)
    @property.account_id = current_account.id

    respond_to do |format|
      if @property.save
        format.html { redirect_to @property, notice: 'Property was successfully created.' }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1
  # PATCH/PUT /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html do
          redirect_to @property, notice: 'Property was successfully
          updated.'
        end
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit }
        format.json do
          render json: @property.errors, status:
          :unprocessable_entity
        end
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.json
  def destroy
    @property.destroy
    respond_to do |format|
      format.html do
        redirect_to properties_url, notice: 'Property was successfully
        destroyed.'
      end
      format.json { head :no_content }
    end
  end

  def email_agent
    # trigger email send
    agent_id = params[:agent_id]
    first_name = params[:first_name]
    last_name = params[:last_name]
    email = params[:email]
    message = params[:message]

    ContactMailer.email_agent(agent_id, first_name, last_name, email, message).deliver_now

    # response to script
    respond_to do |format|
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_property
    @property = Property.find(params[:id])
  end

  def set_sidebar
    @show_sidebar = true
  end

  # Only allow a list of trusted parameters through.
  def property_params
    params.require(:property).permit(:name,  :address, 
                                     :price, :rooms, :bathrooms, :photo
                                     
                                   )
  end
end

app/helpers/properties_helper.rb
# frozen_string_literal: true

module PropertiesHelper
    def property_thumbnail(property)
      img =  'placeholder.jpg'
      image_tag img, class: 'property-thumb'
    end
  
    def property_thumbnail_url(property)
      asset_url('placeholder.jpg')
    end
  
    def property_photo_url(property)
      asset_url('placeholder.jpg')
    end
  end

app/views/properties/_agent_details.html.erb
<div class="text-center border p-4 pb-4 ml-lg-4">
  <div class="mb-2">
    <%= profile_picture @agent %>
  </div>
  <h3 class="h4 m-0"><%= @agent.full_name %></h3>
  <p><%= @agent.company %></p>
  <div class="row">
    <div class="col-12">
      <button class="btn btn-block btn-info text-uppercase mb-3" id="show-tel" data-telephone="<%= @agent.telephone %>"><i class="fas fa-phone mr-2"></i><span>Call</span></button>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 pr-1">
      <%= link_to "Profile", profile_path(@agent.id), class: "btn btn-secondary text-uppercase btn-block" %>
    </div>
    <div class="col-md-6 pl-1">
      <button class="btn btn-block btn-success text-uppercase" data-toggle="modal" data-target="#contact-modal"><i class="fas fa-envelope mr-2"></i>Email</button>
    </div>
  </div>
</div>

app/views/properties/_form.html.erb
<%= form_with(model: property, local: true) do |form| %>
<%# <%= render "layouts/validation", item: @property %> %>

<div class="form-group">
  <%= form.label :name %>
  <%= form.text_field :name, class: "form-control" %>
</div>

<div class="form-group">
  <%= form.label :details %>
  <%= form.text_area :details, class: "form-control" %>
</div>

<%# <div class="form-group">
  <%= form.label :for_sale %>
  <%# <%= form.select :for_sale, options_for_select({ "Yes" => true, "No" => false }, @property.for_sale), class: "form-control" %> %>
<%# </div> %> %>

<%# <div class="form-group">
  <% opts = @property.for_sale? ? { "Available" => "available", "Sold" => "sold"} : { "Available" => "available", "Leased" => "leased"} %>
  <%# <%= form.label :status %> %>
  <%# <%= form.select :status, options_for_select(opts, @property.status), class: "form-control" %>
<%# </div> %> %> %>

<div class="form-group">
  <%= form.label :address %>
  <%= form.text_field :address, class: "form-control" %>
</div>

<div class="form-group">
  <%= form.label :price, "Total Price (for sale) / Monthly Price (rental)" %>
  <%= form.number_field :price, class: "form-control" %>
</div>

<div class="form-group">
  <%= form.label :available_date %>
  <%= form.date_field :available_date, class: "form-control" %>
</div>

<div class="form-group">
  <%= form.label :parking_spaces %>
  <%= form.number_field :parking_spaces, class: "form-control" %>
</div>

<div class="form-group">
  <%= form.label :rooms %>
  <%= form.number_field :room, class: "form-control" %>
</div>

<div class="form-group">
  <%= form.label :bathrooms %>
  <%= form.number_field :bathroom, class: "form-control" %>
</div>

<div class="form-group">
  <%= form.label :photo %>
  <%= form.file_field :photo, class: "form-control" %>
  <%= form.hidden_field :photo_cache %>
  <% if @property.photo.present? %>
  <%= image_tag @property.photo.thumbnail.url, class: "mt-4" %>
  <% end %>
</div>

<div class="form-group">
  <%= form.submit "Save Property", class: "btn btn-success" %>
</div>
<% end %>

app/views/properties/_list.html.erb
<% properties.each do |property| %>
<div class="col-4">
  <div class="property border">

    <%# <!--<div class="property-thumb" style="background-image:url('<%= property_thumbnail_url(property)')">--> %> %>
    <%# <div class="property-thumb" style="background-image:url('<%= property_thumbnail_url(property)')"> %>
      <!-- FIX THIS PROPERTY THUMBNAIL URL -->
      <%# <%= link_to "", property_path(property) %> %>
    <%# </div> %> %>

    <div class="property-summary p-3">
      <h3 class="h5"><%= link_to property.name,property_path(property), class: "text-dark" %></h3>

      <span class="mr-2">
        <%= property.rooms %>
        <i class="fas fa-bed text-muted ml-1"></i>
      </span>
      <span class="mr-2">
        <%= property.bathrooms %>
        <i class="fas fa-bath text-muted ml-1"></i>
      </span>
      <%# <span>
        <%= property.parking_spaces %>
        <%# <i class="fas fa-car text-muted ml-1"></i> %>
      <%# </span> %> %>

      <p class="mt-2"><%= property.address %></p>
    </div>
  </div>
</div>
<% end %>

app/views/properties/_profile_contact_details.html.erb
<div class="text-center">
  <div class="mb-2">
    <%= profile_picture agent %>
  </div>
  <h3 class="h4 m-0"><%= agent.full_name %></h3>
  <p><%= agent.company %></p>

  <div class="row justify-content-md-center">
    <div class="col-md-10">
      <button class="btn btn-block btn-info text-uppercase mb-1" id="show-tel" data-telephone="<%= agent.telephone %>"><i class="fas fa-phone mr-2"></i><span>Call</span></button>
    </div>
    <div class="col-md-10">
      <button class="btn btn-block btn-success text-uppercase" data-toggle="modal" data-target="#contact-modal"><i class="fas fa-envelope mr-2"></i>Email</button>
    </div>
  </div>
</div>

app/views/properties/_send_email_modal.html.erb
<div id="<%= dom_id property %>">
  <p>
    <strong>Name:</strong>
    <%= property.name %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= property.address %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= property.price %>
  </p>

  <p>
    <strong>Rooms:</strong>
    <%= property.rooms %>
  </p>

  <p>
    <strong>Bathrooms:</strong>
    <%= property.bathrooms %>
  </p>

</div>

app/views/properties/edit.html.erb
<h1>Editing property</h1>

<%= render "form", property: @property %>

app/views/properties/index.html.erb
<h1 class="h3">Properties</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Price</th>
      <th>Rooms</th>
      <th>Bathrooms</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @properties.each do |property| %>
    <tr>
      <td><%= property.name %></td>
      <td><%= property.address %></td>
      <td><%= property.price %></td>
      <td><%= property.rooms %></td>
      <td><%= property.bathrooms %></td>
      <td><%= link_to 'Show', property %></td>
      <td><%= link_to 'Edit', edit_property_path(property) %></td>
      <td><%= link_to 'Destroy', property, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Property', new_property_path, class: "btn btn-success" %>

app/views/properties/new.html.erb
<h1 class="h3">New Property</h1>

<%= render 'form', property: @property %>
<%= link_to 'Back', properties_path %>

app/views/properties/show.html.erb
<div class="property-main-photo" style="background-image:url('<%= property_photo_url @property %>')">
  <div class="photo-overlay">
  </div>
</div>

<div class="container">
  <div class="row">
    <div class="col-md-8">
      <div class="row">
        <div class="col-lg-5">
          <%# <p class="h4 mb-0"><%= @property.for_sale? ? "For Sale" : "For Rent" %></p> %>
          <p class="mb-2"><%= @property.address %></p>
          <%# <p class="h2 mb-3">
            <% if @property.for_sale? %>
            <%# <%= @property.price > 0 ? number_to_currency(@property.price, precision: 0) : "Offers accepted" %> %>
            <%# <% else %> %>
            <%# <%= @property.price > 0 ? number_to_currency(@property.price, precision: 0) : "Open for enquiries" %> / month %>
            <%# <% end %> %>
          <%# </p> %> %>
        </div>
        <div class="col-lg-7 text-center">
          <div class="row mt-sm-3 bg-light p-3">
            <div class="col-4">
              <i class="fas fa-bed text-muted m-0"></i><br />
              <small><%= @property.rooms %> Rooms</small>
            </div>
            <div class="col-4">
              <i class="fas fa-bath text-muted ml-1"></i><br />
              <small><%= @property.bathrooms %> Bathrooms</small>
            </div>
            <%# <div class="col-4"> %>
              <%# <i class="fas fa-car"></i><br /> %>
              <%# <small><%= @property.parking_spaces %> Parking</small> %>
            <%# </div> %>
          </div>
        </div>
      </div>
      <div class="row border-top border-bottom mt-5 mb-4 pt-4 pb-4">
        <%# <div class="col-6">
          <% if @property.for_sale? %>
          <%# <b class="text-success">Est. Monthly Reapayments of <%= number_to_currency(((@property.price) / 360) * 0.90, precision: 0) %>*</b> %>
          <%# <% else %> %>
          <%# <b class="text-success">Available from <%= @property.available_date.strftime("%a,") <%= @property.available_date.day.ordinalize %> 
          <%# <%= @property.available_date.strftime("%B") </b> %> %> %> %>
          <%# <%end%> %>
        <%# </div> %> %>
        <div class="col-6 text-right">
          <b><%= link_to "Can I afford this property?", "#", class: "text-success"%></b>
        </div>
      </div>

      <div class="row">
        <div class="col">
          <p class="h3"><b><%= @property.name %></b></p>
          <p class="h5">Property Description</p>
          <div id="prop-details">
            <%# <%= simple_format @property.details %> %>
          </div>
          <button class="btn btn-outline-info mt-3" id="toggleDetails">Show more</button>
          <%# <% if @property.for_sale? %> %>
          <%# <p class="mt-5">*This rate is based on a 30 year mortgage., after paying an initial 10% downpayment. Shorter term mortgages would require a higher monthly repayment.</p> %>
          <%# <% end %> %>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <%# <%= render "properties/agent_details" %> %>

      <iframe class="ml-lg-4 mt-3" width="320" height="240" frameborder="0" style="border:0" src="https://www.google.com/maps/embed/v1/place?key=AIzaSyB1as2uf4ut2rf6f4-Xz57i2J80fJsOTrs&q=<%= @property.address.to_param %>" allowfullscreen></iframe>
    </div>
  </div>

  <section class="mt-5 mb-5">
    <div class="container" bis_skin_checked="1">
      <div class="row" bis_skin_checked="1">
        <div class="col-12">
          <p class="h3 mb-3">Other properties by this agent</p>
        </div>
        <%= render "properties/list", properties: @agent_properties %>
      </div>
    </div>
  </section>
</div>

<%# <%= render "properties/send_email_modal", agent: @agent %> %>